disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Blowfish"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  copyright = "Website Registration and Filing Number: [冀ICP备2022002900号-1](https://beian.miit.gov.cn/)"

[params.author]
  name = "Jehol Fenuth"
  email = "zhangzhewen@jehol-ppx.com"
  image = "img/blowfish_logo.png"
  imageQuality = 96
  headline = "Ambitious & Angry Uth"
  bio = "A little bit about you"
  links = [
    { tiktok = "https://www.douyin.com/user/MS4wLjABAAAAPsab0-D_BUwnWHTlhNS8fHsKGZrkOqTQ_Ou0m6sTgILQPeKJOJk-e8EPn90cECBd" },
    { github = "https://github.com/ppxinashin" },
    { telegram = "https://t.me/jehol_ppx" },
    { x-twitter = "https://x.com/jehol_fenuth" },
    { youtube = "https://www.youtube.com/@%E7%83%AD%E6%B2%B3fen%E9%9D%92" },
  ]
