disabled = false
languageCode = "zh"
languageName = "中文"
weight = 1
title = "热河fen青"

[params]
  displayName = "简体中文"
  isoCode = "zh"
  rtl = false
  dateFormat = "2006-01-02"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  copyright = "网站注册备案号：[冀ICP备2022002900号-1](https://beian.miit.gov.cn/)"

[params.author]
  name = "热河fen青"
  email = "zhangzhewen@jehol-ppx.com"
  image = "img/blowfish_logo.png"
  imageQuality = 96
  headline = "是奋青，亦是愤青"
  bio = "A little bit about you"
  links = [
    { tiktok = "https://www.douyin.com/user/MS4wLjABAAAAPsab0-D_BUwnWHTlhNS8fHsKGZrkOqTQ_Ou0m6sTgILQPeKJOJk-e8EPn90cECBd" },
    { github = "https://github.com/ppxinashin" },
    { telegram = "https://t.me/jehol_ppx" },
    { x-twitter = "https://x.com/jehol_fenuth" },
    { youtube = "https://www.youtube.com/@%E7%83%AD%E6%B2%B3fen%E9%9D%92" },
  ]
